### ISSUE TITLE
USB Host Msc 这个例程中插拔U盘的中断有问题，刚开始可以正常识别，过一会就不能产生任何事件了

### ISSUE THREAD

**Issue by LiuChenghu** [STMicroelectronics/x-cube-azrtos-f4#4]
**Caution**

The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post your report to the **ST Community** in the STM32 MCUs dedicated [page](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus).

**Describe the set-up**

 * The board (either ST RPN reference or your custom board)
 * IDE or at least the compiler and its version

**Describe the bug (skip if none)**

**How to reproduce the bug (skip if none)**

1. Indicate the global behavior of your application project
2. List the modules that you suspect to be the cause of the problem (Drivers, BSP, MW...)
3. Describe the use case that generates the problem
4. How we can reproduce the problem

**Additional context**

If you have a first analysis, an enhancement, a fix or a patch, thank you to share your proposal.

**Screenshots**

**Comment by ALABSTM** [comment]
Hi @LiuChenghu,

The title of the issue should be in English. Would you mind updating it?

Thanks,

**Comment by ALABSTM** [comment]
Hi @LiuChenghu,

We closed this issue as we expect titles and descriptions in English. Thank you for your comprehension. Do not hesitate to post your issue again, in English this time.

With regards,
